In [19]:
import kagglehub
import pandas as pd
import numpy as np

traffic_df = pd.read_csv("Metro_Interstate_Traffic_Volume.csv")
df = pd.DataFrame(traffic_df)

y = traffic_df['traffic_volume']
X = traffic_df.drop('traffic_volume', axis=1)
df.head(10)

,traffic_volume,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time
0,5545,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,02-10-2012 09:00
1,4516,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,02-10-2012 10:00
2,4767,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,02-10-2012 11:00
3,5026,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,02-10-2012 12:00
4,4918,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,02-10-2012 13:00
5,5181,NaN,291.72,0.0,0.0,1,Clear,sky is clear,02-10-2012 14:00
6,5584,NaN,293.17,0.0,0.0,1,Clear,sky is clear,02-10-2012 15:00
7,6015,NaN,293.86,0.0,0.0,1,Clear,sky is clear,02-10-2012 16:00
8,5791,NaN,294.14,0.0,0.0,20,Clouds,few clouds,02-10-2012 17:00
9,4770,NaN,293.10,0.0,0.0,20,Clouds,few clouds,02-10-2012 18:00

# Dataset analysis and preparation
Since the data is not all numbers, it is required to convert the qualitative categories into quantitative lists.

In [53]:
df['holiday'].unique()

df['isHoliday'] = pd.notna(df['holiday'])
unique_weathers = df['weather_main'].values
print(df['weather_main'].unique())
df['weather_cat'] = pd.factorize(unique_weathers)[0]



df.head(10)

['Clouds' 'Clear' 'Rain' 'Drizzle' 'Mist' 'Haze' 'Fog' 'Thunderstorm'
 'Snow' 'Squall' 'Smoke']

,traffic_volume,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,isHoliday,weather_cat
0,5545,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,02-10-2012 09:00,False,0
1,4516,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,02-10-2012 10:00,False,0
2,4767,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,02-10-2012 11:00,False,0
3,5026,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,02-10-2012 12:00,False,0
4,4918,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,02-10-2012 13:00,False,0
5,5181,NaN,291.72,0.0,0.0,1,Clear,sky is clear,02-10-2012 14:00,False,1
6,5584,NaN,293.17,0.0,0.0,1,Clear,sky is clear,02-10-2012 15:00,False,1
7,6015,NaN,293.86,0.0,0.0,1,Clear,sky is clear,02-10-2012 16:00,False,1
8,5791,NaN,294.14,0.0,0.0,20,Clouds,few clouds,02-10-2012 17:00,False,0
9,4770,NaN,293.10,0.0,0.0,20,Clouds,few clouds,02-10-2012 18:00,False,0